version: '3.7'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=metabase_root
      - MYSQL_DATABASE=metabase
      - MYSQL_USER=metabase
      - MYSQL_PASSWORD=metabase_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - trino-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse
    ports:
      - '8123:8123' # HTTP interface
      - '9002:9000' # Native TCP interface
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      #- ./clickhouse-s3.xml:/etc/clickhouse-server/config.d/s3.xml:ro
      # - ./clickhouse-logs:/var/log/clickhouse-server # Activate if you want to see logs on your repo
      - ./infra/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
    networks:
      - trino-network

  minio:
    hostname: minio
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001" 
    networks:
      - trino-network

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase-data
      #- ./metabase-plugins:/plugins
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER: metabase
      MB_DB_PASS: metabase_pass
      MB_DB_HOST: mariadb
    networks:
      - trino-network

  # minio-init:
  #   image: minio/mc:latest
  #   container_name: minio-init
  #   entrypoint: >
  #     /bin/sh -c '
  #     set -e
  #     echo "Waiting for MinIO to be ready..."
  #     mc alias set myminio http://minio:9000 minio minio123 
  #     echo "MinIO is ready. Creating buckets..."
  #     mc mb -p myminio/bucket1 || true
  #     mc mb -p myminio/bucket2 || true
  #     mc mb -p myminio/bucket3 || true
  #     echo "Buckets created."
  #     exit 0
  #     '
  #   networks:
  #     - trino-network
  #   depends_on:
  #     - minio

  # Kafka and Zookeeper (from kafka-standalone)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 14G
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"      # Internal listener
      - "9094:9094"      # External listener
    environment:
      KAFKA_LOG_RETENTION_MS: 3600000
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094 #PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT 
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"] #"localhost:9092"
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  minio-data:
    driver: local
  clickhouse-data:
    driver: local
  metabase-data:
    driver: local
  mariadb-data:
    driver: local

networks:
  trino-network:
    driver: bridge
  kafka-network:
    driver: bridge